layout: default
name: Voron Documentation
description: Voron Official and Community Documentation
logo: "/images/voron_design_logo.png"
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
color_scheme: voron-dark
search_enabled: true
search.button: true
aux_links:
  "Voron Documentation on GitHub":
    - "https://github.com/VoronDesign/Voron-Documentation"
  "VoronDesign Home":
    - "https://vorondesign.com"

